package com.hibernate.entities;



import java.util.HashSet;
import java.util.Set;

/**
 * Client generated by hbm2java
 */
public class Client  implements java.io.Serializable {


     private int idClient;
     private String idTypeClient;
     private String pwdUser;
     private String nom;
     private String prenom;
     private String address;
     private Integer telf;
     private String email1Used;
     private Set clientDecbugs = new HashSet(0);

    public Client() {
    }

	
    public Client(int idClient) {
        this.idClient = idClient;
    }
    public Client(int idClient, String idTypeClient, String pwdUser, String nom, String prenom, String address, Integer telf, String email1Used, Set clientDecbugs) {
       this.idClient = idClient;
       this.idTypeClient = idTypeClient;
       this.pwdUser = pwdUser;
       this.nom = nom;
       this.prenom = prenom;
       this.address = address;
       this.telf = telf;
       this.email1Used = email1Used;
       this.clientDecbugs = clientDecbugs;
    }
   
    public int getIdClient() {
        return this.idClient;
    }
    
    public void setIdClient(int idClient) {
        this.idClient = idClient;
    }
    public String getIdTypeClient() {
        return this.idTypeClient;
    }
    
    public void setIdTypeClient(String idTypeClient) {
        this.idTypeClient = idTypeClient;
    }
    public String getPwdUser() {
        return this.pwdUser;
    }
    
    public void setPwdUser(String pwdUser) {
        this.pwdUser = pwdUser;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public Integer getTelf() {
        return this.telf;
    }
    
    public void setTelf(Integer telf) {
        this.telf = telf;
    }
    public String getEmail1Used() {
        return this.email1Used;
    }
    
    public void setEmail1Used(String email1Used) {
        this.email1Used = email1Used;
    }
    public Set getClientDecbugs() {
        return this.clientDecbugs;
    }
    
    public void setClientDecbugs(Set clientDecbugs) {
        this.clientDecbugs = clientDecbugs;
    }




}


