package com.hibernate.entities;




/**
 * ClientDecbug generated by hbm2java
 */
public class ClientDecbug  implements java.io.Serializable {


     private Integer idClientDecbug;
     private Client client;
     private Decbug decbug;

    public ClientDecbug() {
    }

    public ClientDecbug(Client client, Decbug decbug) {
       this.client = client;
       this.decbug = decbug;
    }
   
    public Integer getIdClientDecbug() {
        return this.idClientDecbug;
    }
    
    public void setIdClientDecbug(Integer idClientDecbug) {
        this.idClientDecbug = idClientDecbug;
    }
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }
    public Decbug getDecbug() {
        return this.decbug;
    }
    
    public void setDecbug(Decbug decbug) {
        this.decbug = decbug;
    }




}


