package com.hibernate.entities;


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Decbug generated by hbm2java
 */
public class Decbug  implements java.io.Serializable {


     private int idDecbug;
     private Ticket ticket;
     private User user;
     private Date datedebut;
     private Date datefin;
     private String titre;
     private String description;
     private String activeDecbug;
     private String rqActiveDecbug;
     private Set clientDecbugs = new HashSet(0);

    public Decbug() {
    }

	
    public Decbug(int idDecbug) {
        this.idDecbug = idDecbug;
    }
    public Decbug(int idDecbug, Ticket ticket, User user, Date datedebut, Date datefin, String titre, String description, String activeDecbug, String rqActiveDecbug, Set clientDecbugs) {
       this.idDecbug = idDecbug;
       this.ticket = ticket;
       this.user = user;
       this.datedebut = datedebut;
       this.datefin = datefin;
       this.titre = titre;
       this.description = description;
       this.activeDecbug = activeDecbug;
       this.rqActiveDecbug = rqActiveDecbug;
       this.clientDecbugs = clientDecbugs;
    }
   
    public int getIdDecbug() {
        return this.idDecbug;
    }
    
    public void setIdDecbug(int idDecbug) {
        this.idDecbug = idDecbug;
    }
    public Ticket getTicket() {
        return this.ticket;
    }
    
    public void setTicket(Ticket ticket) {
        this.ticket = ticket;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Date getDatedebut() {
        return this.datedebut;
    }
    
    public void setDatedebut(Date datedebut) {
        this.datedebut = datedebut;
    }
    public Date getDatefin() {
        return this.datefin;
    }
    
    public void setDatefin(Date datefin) {
        this.datefin = datefin;
    }
    public String getTitre() {
        return this.titre;
    }
    
    public void setTitre(String titre) {
        this.titre = titre;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getActiveDecbug() {
        return this.activeDecbug;
    }
    
    public void setActiveDecbug(String activeDecbug) {
        this.activeDecbug = activeDecbug;
    }
    public String getRqActiveDecbug() {
        return this.rqActiveDecbug;
    }
    
    public void setRqActiveDecbug(String rqActiveDecbug) {
        this.rqActiveDecbug = rqActiveDecbug;
    }
    public Set getClientDecbugs() {
        return this.clientDecbugs;
    }
    
    public void setClientDecbugs(Set clientDecbugs) {
        this.clientDecbugs = clientDecbugs;
    }




}


