package com.hibernate.entities;


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Ticket generated by hbm2java
 */
public class Ticket  implements java.io.Serializable {


     private int idTicket;
     private Integer code;
     private Date dateDebutTicket;
     private Date dateDubetTicket;
     private String description;
     private String activeTicket;
     private String rqActiveTicket;
     private Set decbugs = new HashSet(0);

    public Ticket() {
    }

	
    public Ticket(int idTicket) {
        this.idTicket = idTicket;
    }
    public Ticket(int idTicket, Integer code, Date dateDebutTicket, Date dateDubetTicket, String description, String activeTicket, String rqActiveTicket, Set decbugs) {
       this.idTicket = idTicket;
       this.code = code;
       this.dateDebutTicket = dateDebutTicket;
       this.dateDubetTicket = dateDubetTicket;
       this.description = description;
       this.activeTicket = activeTicket;
       this.rqActiveTicket = rqActiveTicket;
       this.decbugs = decbugs;
    }
   
    public int getIdTicket() {
        return this.idTicket;
    }
    
    public void setIdTicket(int idTicket) {
        this.idTicket = idTicket;
    }
    public Integer getCode() {
        return this.code;
    }
    
    public void setCode(Integer code) {
        this.code = code;
    }
    public Date getDateDebutTicket() {
        return this.dateDebutTicket;
    }
    
    public void setDateDebutTicket(Date dateDebutTicket) {
        this.dateDebutTicket = dateDebutTicket;
    }
    public Date getDateDubetTicket() {
        return this.dateDubetTicket;
    }
    
    public void setDateDubetTicket(Date dateDubetTicket) {
        this.dateDubetTicket = dateDubetTicket;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getActiveTicket() {
        return this.activeTicket;
    }
    
    public void setActiveTicket(String activeTicket) {
        this.activeTicket = activeTicket;
    }
    public String getRqActiveTicket() {
        return this.rqActiveTicket;
    }
    
    public void setRqActiveTicket(String rqActiveTicket) {
        this.rqActiveTicket = rqActiveTicket;
    }
    public Set getDecbugs() {
        return this.decbugs;
    }
    
    public void setDecbugs(Set decbugs) {
        this.decbugs = decbugs;
    }




}


