package com.hibernate.entities;




/**
 * TypeUser generated by hbm2java
 */
public class TypeUser  implements java.io.Serializable {


     private String idTypeUser;

    public TypeUser() {
    }

    public TypeUser(String idTypeUser) {
       this.idTypeUser = idTypeUser;
    }
   
    public String getIdTypeUser() {
        return this.idTypeUser;
    }
    
    public void setIdTypeUser(String idTypeUser) {
        this.idTypeUser = idTypeUser;
    }




}


