package com.hibernate.entities;




/**
 * TypeClient generated by hbm2java
 */
public class TypeClient  implements java.io.Serializable {


     private String idTypeClient;

    public TypeClient() {
    }

    public TypeClient(String idTypeClient) {
       this.idTypeClient = idTypeClient;
    }
   
    public String getIdTypeClient() {
        return this.idTypeClient;
    }
    
    public void setIdTypeClient(String idTypeClient) {
        this.idTypeClient = idTypeClient;
    }




}


